language: php

php:
  - "7.2"
  - "7.1"
  - "7.0"
  - "5.6"

before_script:
  - composer install --prefer-source --no-interaction

script:
  - phpunit -c phpunit.xml --coverage-text

notifications:
    email: false
